### ISSUE TITLE
review dependency to have io.netty in sync with latest selenium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-api#25]
let's update dependencies to use the same io.netty here and in carina-webdriver.
4.1.80 and 4.1.84 io.netty in classpath might lead to below exception:
```
23:39:31  Caused by: org.openqa.selenium.WebDriverException: 
23:39:31  java.lang.reflect.InvocationTargetException
23:39:31  Build info: version: '4.7.0', revision: '0a5b49d16f'
23:39:31  System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.25-37.47.amzn2023.x86_64', java.version: '11.0.19'
23:39:31  Driver info: driver.version: IOSDriver
23:39:31  	at com....etailsTab(DisneyPlusAnthologyQATest.java:284)
23:39:31  Caused by: java.lang.reflect.InvocationTargetException
23:39:31  	at com....DetailsTab(DisneyPlusAnthologyQATest.java:284)
23:39:31  Caused by: java.lang.NoClassDefFoundError: io/netty/handler/codec/DefaultHeaders$ValueValidator
23:39:31  	at com...DetailsTab(DisneyPlusAnthologyQATest.java:284)
23:39:31  Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.DefaultHeaders$ValueValidator
23:39:31  	at com....DetailsTab(DisneyPlusAnthologyQATest.java:284)
```

**Comment by akamarouski** [comment]
There are no `io.netty` in the release version
